-- MySQL Script generated by MySQL Workbench
-- Tue Oct 12 15:34:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Trabajo_individual_entregable
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Trabajo_individual_entregable
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Trabajo_individual_entregable` DEFAULT CHARACTER SET utf8 ;
USE `Trabajo_individual_entregable` ;

-- -----------------------------------------------------
-- Table `Trabajo_individual_entregable`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabajo_individual_entregable`.`usuarios` (
  `id (PK)` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id (PK)`))
ENGINE = InnoDB;
INSERT INTO `usuarios` VALUES (1,'Funes Lucas','funeslucas@outlook.com'),(2,'Matias Gonzales','mati@hotmail.com'),(3,'Federico Gomez','fede@outlook.com'),(4,'Luciano Martinez','lucho@hotmail.com'),(5,'Sebastian Jimenez','seba2020@gmail.com'),(6,'Marcos Dominguez','maquitos_clavito@outlook.com'),(7,'Martina Tevez','martuppache@gmail.com'),(8,'Francisco Ventura','francis2020@gmail.com'),(9,'Florencia Otero','floooopy@gmail.com'),(10,'Noelia Correa','noeco@hotmail.com');

-- -----------------------------------------------------
-- Table `Trabajo_individual_entregable`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabajo_individual_entregable`.`notas` (
  `id (PK)` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `fecha_de_creacion` DATETIME NULL,
  `fecha_de_edicion` DATETIME NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `eliminar` INT NULL,
  `id_usuario (FK)` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id (PK)`),
  INDEX `usuario_idx` (`id_usuario (FK)` ASC) ,
  CONSTRAINT `usuario`
    FOREIGN KEY (`id_usuario (FK)`)
    REFERENCES `Trabajo_individual_entregable`.`usuarios` (`id (PK)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
INSERT INTO `notas` (titulo, descripcion,`id_usuario (FK)`, id_categoria) VALUES ('Titulo de nota 1', 'Descripcion nota 1', 1, 5),('Titulo de nota 2', 'Descripcion nota 2', 9, 5),('Titulo de nota 3', 'Descripcion nota 3', 9, 2),('Titulo de nota 4', 'Descripcion nota 4', 2, 9),('Titulo de nota 5', 'Descripcion nota 5', 1, 3),('Titulo de nota 6', 'Descripcion nota 6', 7, 3),('Titulo de nota 7', 'Descripcion nota 7', 4, 10),('Titulo de nota 8', 'Descripcion nota 8', 10, 3),('Titulo de nota 9', 'Descripcion nota 9', 10, 1),('Titulo de nota 10', 'Descripcion nota 10', 6, 7);

-- -----------------------------------------------------
-- Table `Trabajo_individual_entregable`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabajo_individual_entregable`.`categorias` (
  `id (PK)` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id (PK)`))
ENGINE = InnoDB;
INSERT INTO `categorias` VALUES (1,'Musica'),(2,'Deporte'),(3,'Cultura'),(4,'Arte'),(5,'Sociedad'),(6,'Arte'),(7,'Politica'),(8,'Cocina'),(9,'Economia'),(10,'Entretenimiento');

-- -----------------------------------------------------
-- Table `Trabajo_individual_entregable`.`notas_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Trabajo_individual_entregable`.`notas_categorias` (
  `id_notas (FK)` INT NOT NULL,
  `id_categorias (FK)` INT NOT NULL,
  INDEX `categoria_idx` (`id_categorias (FK)` ASC) ,
  INDEX `notas_idx` (`id_notas (FK)` ASC) ,
  CONSTRAINT `categoria`
    FOREIGN KEY (`id_categorias (FK)`)
    REFERENCES `Trabajo_individual_entregable`.`categorias` (`id (PK)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `notas`
    FOREIGN KEY (`id_notas (FK)`)
    REFERENCES `Trabajo_individual_entregable`.`notas` (`id (PK)`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
